"""절차적 메시 도구 (numpy 만 사용): OBJ/이미지 저장, 튜브·바위·잎·풀잎 등 기본 도형.

Gazebo(ogre2) 가 읽는 OBJ(v/vt/vn/f)를 직접 쓴다. 재질은 SDF 쪽에서 지정하므로 MTL 은 만들지 않는다.
양면이 보여야 하는 얇은 물체(잎, 풀잎)는 앞/뒷면 삼각형을 모두 만든다 (렌더링·LiDAR 모두 양쪽에서 보이게).

규약
  - 정점 배열 verts: (N, 3) float [m], 면 배열 faces: (M, 3) int (0 부터 시작하는 정점 번호, 반시계 = 앞면),
    uv: (N, 2) 텍스처 좌표. 도형 함수는 (verts, faces[, uv]) 튜플을 돌려주고 Mesh.add(*...) 로 붙인다.
  - 좌표는 Gazebo 월드와 같은 오른손 좌표계, z 가 위.
사용처: terrain.py(지형), vegetation.py(나무·풀·자갈·바위·숲). 파라미터는 없고 호출하는 쪽이 크기를 정한다.

참고
  - Wavefront OBJ 형식 (v / vt / vn / f, 번호는 1 부터)
  - PNG 명세 (W3C PNG Specification / RFC 2083): Pillow 가 없을 때 직접 쓰는 PNG 청크 구조
  - T. Möller, J. F. Hughes, "Efficiently Building a Matrix to Rotate One Vector to Another",
    Journal of Graphics Tools 4(4), 1999 (rot_from_to)
  - R. L. Bishop, "There is More than One Way to Frame a Curve", American Mathematical Monthly 82(3), 1975
    (tube 의 평행이동(parallel transport) 프레임)
"""
from __future__ import annotations

import math
import os
import struct
import zlib

import numpy as np


class Mesh:
    """삼각형 메시 누적기. add() 로 조각을 붙이고 arrays() 로 합친다."""

    def __init__(self):
        """빈 메시. 조각별 배열을 리스트로 모아 두었다가 arrays() 에서 한 번에 합친다 (반복 concatenate 방지)."""
        self._v, self._f, self._uv = [], [], []
        self._n = 0                                # 지금까지 붙인 정점 수 (다음 조각의 면 번호 오프셋)

    def add(self, verts, faces, uv=None):
        """조각 추가. verts (N,3) [m], faces (M,3) 조각 안 번호, uv (N,2) 없으면 0. 체이닝용으로 self 반환."""
        verts = np.asarray(verts, dtype=np.float64).reshape(-1, 3)
        faces = np.asarray(faces, dtype=np.int64).reshape(-1, 3)
        if uv is None:
            uv = np.zeros((len(verts), 2))
        self._v.append(verts)
        self._f.append(faces + self._n)            # 조각 안 번호 → 전체 번호
        self._uv.append(np.asarray(uv, dtype=np.float64).reshape(-1, 2))
        self._n += len(verts)
        return self

    def add_mesh(self, other: 'Mesh', rot=None, trans=None, scale=1.0):
        """다른 메시를 scale → 회전 rot(3×3) → 평행이동 trans(3,) [m] 순서로 변환해 붙인다."""
        v, f, uv = other.arrays()
        if len(v) == 0:
            return self
        v = v * scale
        if rot is not None:
            v = v @ np.asarray(rot).T              # 행벡터 정점에 R 적용 = v · Rᵀ
        if trans is not None:
            v = v + np.asarray(trans)
        return self.add(v, f, uv)

    def arrays(self):
        """합친 (verts (N,3), faces (M,3) int64, uv (N,2)) 반환. 비어 있으면 크기 0 배열."""
        if not self._v:
            return np.zeros((0, 3)), np.zeros((0, 3), dtype=np.int64), np.zeros((0, 2))
        return np.concatenate(self._v), np.concatenate(self._f), np.concatenate(self._uv)

    def split(self, face_mask) -> tuple['Mesh', 'Mesh']:
        """면 마스크로 (True 면들, False 면들) 두 메시로 나눈다 (정점·UV 유지)."""
        v, f, uv = self.arrays()
        out = []
        for sel in (np.asarray(face_mask, bool), ~np.asarray(face_mask, bool)):
            m = Mesh()
            if sel.any():
                ff = f[sel]
                used = np.unique(ff)                       # 선택된 면이 쓰는 정점만 남긴다
                remap = np.full(len(v), -1)
                remap[used] = np.arange(len(used))         # 옛 정점 번호 → 새 번호
                m.add(v[used], remap[ff], uv[used])
            out.append(m)
        return out[0], out[1]

    @property
    def n_tris(self) -> int:
        """삼각형 수 (렌더링 부하 가늠용)."""
        return int(sum(len(f) for f in self._f))

    def empty(self) -> bool:
        """정점이 하나도 없으면 True (빈 OBJ 파일을 쓰지 않으려고)."""
        return self._n == 0


# ---------------------------------------------------------------- 저장
def vertex_normals(v: np.ndarray, f: np.ndarray) -> np.ndarray:
    """정점 법선 (N,3) 단위벡터: 둘러싼 면 법선의 면적 가중 평균."""
    n = np.zeros_like(v)
    fn = np.cross(v[f[:, 1]] - v[f[:, 0]], v[f[:, 2]] - v[f[:, 0]])     # 면적 가중
    # 외적 크기 = 삼각형 넓이의 2배 → 정규화 없이 더하면 큰 면이 더 큰 가중치를 갖는다
    for k in range(3):
        np.add.at(n, f[:, k], fn)                  # 같은 정점이 여러 번 나와도 모두 더해지게 (n[idx] += 는 중복 무시)
    ln = np.linalg.norm(n, axis=1, keepdims=True)
    ln[ln < 1e-12] = 1.0                           # 쓰이지 않거나 퇴화한 정점: 0 으로 나누기 방지
    return n / ln


def write_obj(path: str, mesh: Mesh, uv: bool = True):
    """mesh 를 Wavefront OBJ 로 저장 (정점 법선 포함). uv=False 면 텍스처 좌표를 빼서 파일을 줄인다."""
    v, f, t = mesh.arrays()
    n = vertex_normals(v, f)
    f1 = f + 1                                     # OBJ 번호는 1 부터
    with open(path, 'w', encoding='ascii') as fh:
        fh.write('# generated by orchard_gazebo.meshes\n')
        np.savetxt(fh, v, fmt='v %.4f %.4f %.4f')
        if uv:
            np.savetxt(fh, t, fmt='vt %.5f %.5f')
        np.savetxt(fh, n, fmt='vn %.3f %.3f %.3f')
        # 정점·UV·법선 번호가 같으므로 각 번호를 반복: [a, b, c] → 'f a/a/a b/b/b c/c/c'
        if uv:
            np.savetxt(fh, np.repeat(f1, 3, axis=1), fmt='f %d/%d/%d %d/%d/%d %d/%d/%d')
        else:
            np.savetxt(fh, np.repeat(f1, 2, axis=1), fmt='f %d//%d %d//%d %d//%d')


def write_image(path: str, rgb: np.ndarray, quality: int = 88) -> str:
    """rgb: HxWx3 float(0~1) 또는 uint8. Pillow 가 있으면 JPEG, 없으면 PNG 로 저장. 실제 경로 반환.
    이미지의 첫 행이 텍스처 v=1 (위쪽) 이 되도록 호출하는 쪽에서 뒤집어 줄 것."""
    img = rgb if rgb.dtype == np.uint8 else (np.clip(rgb, 0, 1) * 255 + 0.5).astype(np.uint8)   # +0.5 = 반올림
    try:
        from PIL import Image
        base, _ = os.path.splitext(path)
        path = base + '.jpg'
        Image.fromarray(img, 'RGB').save(path, quality=quality)
        return path
    except ImportError:
        base, _ = os.path.splitext(path)
        path = base + '.png'
        h, w, _c = img.shape
        raw = b''.join(b'\x00' + img[r].tobytes() for r in range(h))   # 행마다 필터 종류 0(None) 바이트

        def chunk(tag, data):
            """PNG 청크 = 길이(4B, big-endian) + 종류 + 데이터 + CRC32(종류+데이터)."""
            c = struct.pack('>I', len(data)) + tag + data
            return c + struct.pack('>I', zlib.crc32(tag + data) & 0xffffffff)
        with open(path, 'wb') as fh:
            fh.write(b'\x89PNG\r\n\x1a\n')                     # PNG 파일 서명 8 바이트
            # IHDR: 폭, 높이, 비트 깊이 8, 색 종류 2(RGB), 압축 0, 필터 0, 인터레이스 0
            fh.write(chunk(b'IHDR', struct.pack('>IIBBBBB', w, h, 8, 2, 0, 0, 0)))
            fh.write(chunk(b'IDAT', zlib.compress(raw, 6)))
            fh.write(chunk(b'IEND', b''))
        return path


# ---------------------------------------------------------------- 회전
def rot_z(a: float) -> np.ndarray:
    """z 축 둘레 a [rad] 회전행렬 (반시계 +)."""
    c, s = math.cos(a), math.sin(a)
    return np.array([[c, -s, 0], [s, c, 0], [0, 0, 1.0]])


def rot_from_to(a, b) -> np.ndarray:
    """단위벡터 a 를 b 로 보내는 회전행렬.

    a, b 는 길이 3 벡터 (내부에서 정규화). Möller & Hughes(1999) 식 R = I + [v]× + [v]×² / (1 + c),
    v = a × b, c = a · b. a, b 가 거의 반대(c ≈ −1)면 1/(1+c) 가 발산하므로 따로 처리한다.
    """
    a = np.asarray(a, float) / np.linalg.norm(a)
    b = np.asarray(b, float) / np.linalg.norm(b)
    v = np.cross(a, b)
    c = float(np.dot(a, b))
    if c < -0.999999:
        # 반대 방향: a 에 수직인 축 v 둘레 180° 회전 = 2 v vᵀ − I
        axis = np.array([1.0, 0, 0]) if abs(a[0]) < 0.9 else np.array([0, 1.0, 0])
        v = np.cross(a, axis)
        v /= np.linalg.norm(v)
        return 2 * np.outer(v, v) - np.eye(3)
    vx = np.array([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])     # 외적 행렬 [v]×
    return np.eye(3) + vx + vx @ vx / (1 + c)


# ---------------------------------------------------------------- 도형
def tube(points, radii, sides: int = 8, cap_top: bool = True) -> tuple:
    """중심선 points(N×3) 를 따라가는 원뿔대 튜브 (평행이동 프레임). (verts, faces, uv) 반환.

    radii: 각 점의 반지름 (N,) [m], sides: 단면 다각형 변 수, cap_top: 끝점을 부채꼴로 막을지.
    나무 줄기·가지, 지주, 철선, 호스에 쓴다. uv = (둘레 비율 0~1, 중심선 누적 길이 [m]).
    평행이동 프레임은 Frenet 프레임과 달리 곧은 구간에서도 정의되고 비틀림이 적다 (Bishop 1975).
    """
    p = np.asarray(points, float)
    r = np.asarray(radii, float)
    n = len(p)
    tang = np.gradient(p, axis=0)                  # 중앙 차분 접선 (양 끝은 한쪽 차분)
    tang /= np.linalg.norm(tang, axis=1, keepdims=True)
    # 첫 법선: 접선과 평행하지 않은 기준축과의 외적 (접선이 거의 수직이면 x 축을 기준으로)
    ref = np.array([0, 0, 1.0]) if abs(tang[0][2]) < 0.9 else np.array([1.0, 0, 0])
    nrm = np.cross(tang[0], ref)
    nrm /= np.linalg.norm(nrm)
    ang = np.linspace(0, 2 * math.pi, sides, endpoint=False)
    verts, uv = [], []
    seg_len = np.concatenate([[0], np.cumsum(np.linalg.norm(np.diff(p, axis=0), axis=1))])
    for i in range(n):
        if i > 0:       # 평행이동: 이전 법선을 새 접선에 수직이 되게 투영
            nrm = nrm - np.dot(nrm, tang[i]) * tang[i]
            nrm /= np.linalg.norm(nrm)
        bin_ = np.cross(tang[i], nrm)              # 종법선 → (nrm, bin_) 이 단면 평면의 직교 기저
        ring = p[i] + r[i] * (np.outer(np.cos(ang), nrm) + np.outer(np.sin(ang), bin_))
        verts.append(ring)
        uv.append(np.stack([ang / (2 * math.pi), np.full(sides, seg_len[i])], axis=1))
    verts = np.concatenate(verts)
    uv = np.concatenate(uv)
    faces = []
    for i in range(n - 1):                         # 이웃한 두 고리 사이 사각형 = 삼각형 2개
        a0, b0 = i * sides, (i + 1) * sides
        for k in range(sides):
            k1 = (k + 1) % sides
            faces.append((a0 + k, a0 + k1, b0 + k1))
            faces.append((a0 + k, b0 + k1, b0 + k))
    if cap_top:
        c = len(verts)
        verts = np.vstack([verts, p[-1]])
        uv = np.vstack([uv, [0.5, seg_len[-1]]])
        top = (n - 1) * sides
        faces += [(top + k, top + (k + 1) % sides, c) for k in range(sides)]
    return verts, np.array(faces), uv


_ICO_CACHE: dict = {}


def icosphere(subdiv: int = 1) -> tuple:
    """단위 구 근사 (verts, faces). 정이십면체를 subdiv 번 나눈다: 면 수 = 20 × 4^subdiv. 결과는 캐시."""
    if subdiv in _ICO_CACHE:
        return _ICO_CACHE[subdiv]
    t = (1 + 5 ** 0.5) / 2                         # 황금비: 정이십면체 12 정점 = (0, ±1, ±t) 의 순환 치환
    v = [(-1, t, 0), (1, t, 0), (-1, -t, 0), (1, -t, 0), (0, -1, t), (0, 1, t), (0, -1, -t), (0, 1, -t),
         (t, 0, -1), (t, 0, 1), (-t, 0, -1), (-t, 0, 1)]
    f = [(0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11), (1, 5, 9), (5, 11, 4), (11, 10, 2),
         (10, 7, 6), (7, 1, 8), (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9), (4, 9, 5), (2, 4, 11),
         (6, 2, 10), (8, 6, 7), (9, 8, 1)]
    v = [np.array(x, float) / np.linalg.norm(x) for x in v]
    for _ in range(subdiv):
        cache, nf = {}, []

        def mid(i, j):
            """변 (i, j) 의 중점을 구 위로 투영한 정점 번호 (이웃 면과 공유하도록 캐시)."""
            key = (min(i, j), max(i, j))
            if key not in cache:
                m = v[i] + v[j]
                v.append(m / np.linalg.norm(m))
                cache[key] = len(v) - 1
            return cache[key]
        for a, b, c in f:
            ab, bc, ca = mid(a, b), mid(b, c), mid(c, a)
            nf += [(a, ab, ca), (b, bc, ab), (c, ca, bc), (ab, bc, ca)]   # 삼각형 1개 → 4개
        f = nf
    out = (np.array(v), np.array(f))
    _ICO_CACHE[subdiv] = out
    return out


def blob(rng: np.random.Generator, radius, squash=(1.0, 1.0, 1.0), roughness: float = 0.25,
         subdiv: int = 1) -> tuple:
    """울퉁불퉁한 덩어리 (자갈, 바위, 먼 산의 나무 수관).

    radius [m], squash: 축별 배율 (x, y, z), roughness: 반지름 변동 비율 (0 = 매끈한 타원체).
    반환 (verts, faces), 원점 중심.
    """
    v, f = icosphere(subdiv)
    # 무작위 방향 4개의 사인파를 구 표면에 겹쳐 반지름을 흔든다 (2.3 = 구 한 바퀴당 굴곡 수를 정하는 주파수)
    k = rng.normal(size=(4, 3))
    ph = rng.uniform(0, 2 * math.pi, 4)
    disp = 1 + roughness * np.mean(np.sin(v @ k.T * 2.3 + ph), axis=1)
    return v * disp[:, None] * np.asarray(squash) * radius, f


def double_sided(verts, faces, offset: float = 0.0008) -> tuple:
    """앞뒷면 삼각형 (뒷면 정점을 살짝 띄워 법선이 섞이지 않게).

    offset: 뒷면을 법선 반대쪽으로 미는 거리 [m] (기본 0.8 mm). 반환 (정점 2N, 면 2M).
    """
    verts = np.asarray(verts, float)
    faces = np.asarray(faces)
    fn = np.cross(verts[faces[:, 1]] - verts[faces[:, 0]], verts[faces[:, 2]] - verts[faces[:, 0]])
    vn = np.zeros_like(verts)
    for k in range(3):
        np.add.at(vn, faces[:, k], fn)
    ln = np.linalg.norm(vn, axis=1, keepdims=True)
    ln[ln < 1e-12] = 1
    back = verts - vn / ln * offset
    return (np.vstack([verts, back]),
            np.vstack([faces, faces[:, ::-1] + len(verts)]))     # 뒷면은 정점 순서를 뒤집어 반대쪽을 향하게


def leaf_shape(length: float, width: float, fold: float = 0.15) -> tuple:
    """사과잎 한 장(끝이 뾰족한 삼각형): +x 방향으로 뻗고 z 가 윗면. 양면 2 삼각형.
    잎 수가 많아야 수관이 빽빽해 보이므로 잎 하나는 가장 싸게 만든다.
    length, width [m], fold: 잎 양쪽 가장자리를 아래로 접는 정도 (폭 대비 비율)."""
    L, W = length, width
    v = np.array([[0, 0.5 * W, -fold * W], [0, -0.5 * W, -fold * W], [L, 0, 0]])
    return double_sided(v, np.array([[0, 1, 2]]))


def grass_blade(rng: np.random.Generator, height: float, width: float) -> tuple:
    """풀잎 한 장 (밑이 넓고 끝이 한쪽으로 기운 삼각형, 양면 2 삼각형).

    height, width [m]. 기울어짐(높이의 10~45 %)과 방향은 rng 로 무작위. 밑동이 원점.
    """
    lean = rng.uniform(0.1, 0.45) * height
    az = rng.uniform(0, 2 * math.pi)
    d = np.array([math.cos(az), math.sin(az), 0.0])
    side = np.array([-d[1], d[0], 0.0]) * width / 2
    v = np.array([-side, side, d * lean + np.array([0, 0, height])])
    return double_sided(v, np.array([[0, 1, 2]]), offset=0.0005)


def box(size) -> tuple:
    """면마다 정점을 따로 둔 상자 (모서리가 둥글게 음영지지 않게).

    size: (x, y, z) 전체 길이 [m], 원점 중심. 반환 (정점 24, 면 12).
    """
    sx, sy, sz = (s / 2 for s in size)
    quads = [((-1, -1, -1), (-1, 1, -1), (1, 1, -1), (1, -1, -1)), ((-1, -1, 1), (1, -1, 1), (1, 1, 1), (-1, 1, 1)),
             ((-1, -1, -1), (1, -1, -1), (1, -1, 1), (-1, -1, 1)), ((-1, 1, -1), (-1, 1, 1), (1, 1, 1), (1, 1, -1)),
             ((-1, -1, -1), (-1, -1, 1), (-1, 1, 1), (-1, 1, -1)), ((1, -1, -1), (1, 1, -1), (1, 1, 1), (1, -1, 1))]
    v, f = [], []
    for q in quads:
        b = len(v)
        v += [(a * sx, c * sy, d * sz) for a, c, d in q]
        f += [(b, b + 1, b + 2), (b, b + 2, b + 3)]
    return np.array(v, float), np.array(f)
